# vars.yaml
test_data:
  username: "testuser"
  password: "password123"

api_config:
  base_url: "https://api.example.com"
  timeout: 30

environment: "staging"

# HTTP客户端配置
http_clients:
  default:  # 默认客户端配置
    base_url: https://httpbin.org
    headers:
      User-Agent: pytest-dsl-client/1.0
      Accept: application/json
    timeout: 30
    verify_ssl: true
    session: true

  jsonplaceholder:  # JSONPlaceholder API客户端
    base_url: https://jsonplaceholder.typicode.com
    headers:
      User-Agent: pytest-dsl-client/1.0
      Accept: application/json
    timeout: 15
    verify_ssl: true
    session: true
    retry:
      max_retries: 2
      retry_interval: 1
      retry_on_status: [500, 502, 503, 504]

  # 自定义认证客户端配置
  hmac_auth:
    base_url: https://httpbin.org
    headers:
      User-Agent: pytest-dsl-client/1.0
      Accept: application/json
    timeout: 30
    verify_ssl: true
    session: true
    auth:
      type: custom
      provider_name: hmac_aws_auth

  jwt_auth:
    base_url: https://httpbin.org
    headers:
      User-Agent: pytest-dsl-client/1.0
      Accept: application/json
    timeout: 30
    verify_ssl: true
    session: true
    auth:
      type: custom
      provider_name: jwt_refresh_auth

  wechat_auth:
    base_url: https://httpbin.org
    headers:
      User-Agent: pytest-dsl-client/1.0
      Accept: application/json
    timeout: 30
    verify_ssl: true
    session: true
    auth:
      type: custom
      provider_name: wechat_miniapp_auth

  multi_step_auth:
    base_url: https://httpbin.org
    headers:
      User-Agent: pytest-dsl-client/1.0
      Accept: application/json
    timeout: 30
    verify_ssl: true
    session: true
    auth:
      type: custom
      provider_name: multi_step_auth

  # CSRF认证客户端配置
  csrf_auth:
    base_url: https://httpbin.org
    headers:
      User-Agent: pytest-dsl-client/1.0
      Accept: application/json
    timeout: 30
    verify_ssl: true
    session: true
    auth:
      type: custom
      provider_name: csrf_login_auth

  # 内置认证客户端配置
  basic_auth:
    base_url: https://httpbin.org
    headers:
      User-Agent: pytest-dsl-client/1.0
      Accept: application/json
    timeout: 30
    verify_ssl: true
    session: true
    auth:
      type: basic
      username: test_user
      password: test_pass

  token_auth:
    base_url: https://httpbin.org
    headers:
      User-Agent: pytest-dsl-client/1.0
      Accept: application/json
    timeout: 30
    verify_ssl: true
    session: true
    auth:
      type: token
      token: test_token
      scheme: Bearer

  api_key_auth:
    base_url: https://httpbin.org
    headers:
      User-Agent: pytest-dsl-client/1.0
      Accept: application/json
    timeout: 30
    verify_ssl: true
    session: true
    auth:
      type: api_key
      api_key: test_api_key
      key_name: X-Api-Key
      in_header: true

  api_key_query_auth:
    base_url: https://httpbin.org
    headers:
      User-Agent: pytest-dsl-client/1.0
      Accept: application/json
    timeout: 30
    verify_ssl: true
    session: true
    auth:
      type: api_key
      api_key: test_api_key
      in_header: false
      in_query: true
      query_param_name: api_key

# HTTP请求模板
http_templates:
  json_post:
    method: POST
    request:
      headers:
        Content-Type: application/json
      json: {}
    asserts:
      - ["status", "in", [200, 201]]

  api_auth:
    method: POST
    url: /auth/login
    request:
      headers:
        Content-Type: application/json
      json:
        username: ""
        password: ""
    captures:
      token: ["jsonpath", "$.token"]
    asserts:
      - ["status", "eq", 200]
      - ["jsonpath", "$.token", "exists"]

# 测试数据
api_test_data:
  username: test_user
  password: password123
  user_id: 10

# 远程服务器配置（可选）
# 取消注释以下配置来启用自动远程服务器连接
# remote_servers:
#   main_server:
#     url: "http://localhost:8270/"
#     alias: "main"
#     api_key: "your_api_key_here"  # 可选
#     sync_config:                  # 可选
#       sync_global_vars: true
#       sync_yaml_vars: true
#
#   backup_server:
#     url: "http://backup-host:8270/"
#     alias: "backup"