# vars.yaml
test_data:
  username: "testuser"
  password: "password123"

api_config:
  base_url: "https://api.example.com"
  timeout: 30

environment: "staging"

# HTTP客户端配置
http_clients:
  default:  # 默认客户端配置
    base_url: https://httpbin.org
    headers:
      User-Agent: pytest-dsl-client/1.0
      Accept: application/json
    timeout: 30
    verify_ssl: true
    session: true
    auth:
      type: custom
      provider_name: custom_auth
      username: admin
      password: admin
      version: 1.0.1
